### ISSUE TITLE
Clean up top of briefing (If possible) [Read comments]

### ISSUE THREAD

**Issue by VexA3** [RaynorD/DCS-OperationKickoff#12]
If possible, reformat the briefing to have 
Mission Overview, Mission DATA, and Allies Flight
at the bottom of the briefing or out of the way, IE try to format the Situation to the top of the briefing.

**Comment by RaynorD** [comment]
Can't tell what exactly you're suggesting. Welcome info and SRS to get people on comms, then situation, then radio details is an order that everyone I've talked to are happy with.
